apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1-deployment
  namespace: dapr
  labels:
    app: api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
      - name: api1
        image: ghcr.io/brandencward/dapr-demo-api1-arm:latest
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: api1-nodeport
  namespace: dapr
spec:
  type: NodePort
  selector:
    app: api1
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 31111